name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      queries:
        description: 'Write SQL queries'
        required: false
        default: 'false'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install SQLite
        if: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.queries != 'false'}}
        run: sudo apt-get install sqlite3 

      - name: Create SQL queries file ans activate FK
        if: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.queries != 'false'}}
        run: |
          echo "PRAGMA foreign_keys = ON;" > queries.sql
          echo "${{ github.event.inputs.queries }}" | jq -r '.[]' >> queries.sql

      - name: Run SQL queries
        if: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.queries != 'false'}}
        run: |
          set -e
          sqlite3 ./public/CollecTF.db < queries.sql

      - name: Delete SQL queries file
        if: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.queries != 'false'}}
        run: rm queries.sql

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
